/**
 * Command Type Definitions
 *
 * This module defines the TypeScript types for custom commands published
 * from markdown files with frontmatter metadata.
 */

/**
 * Frontmatter data structure extracted from markdown files.
 *
 * All fields are optional as frontmatter may be missing or incomplete.
 */
export interface CommandFrontmatter {
  /**
   * Short description of the command.
   * This will be displayed in the command list and detail pages.
   */
  description?: string

  /**
   * Comma-separated list of allowed tools (e.g., "Read, Write, Edit, Bash").
   * This indicates which tools the command can use.
   */
  "allowed-tools"?: string

  /**
   * Hint for command arguments (e.g., "<youtube-video-id>").
   * This helps users understand what arguments the command expects.
   */
  "argument-hint"?: string
}

/**
 * Complete metadata for a custom command.
 *
 * This combines frontmatter data with derived information (slug, title)
 * and the full markdown content.
 */
export interface CommandMetadata {
  /**
   * URL-safe slug generated from the filename (e.g., "convert-video").
   * Used for routing: /claude-code/commands/:slug
   */
  slug: string

  /**
   * Human-readable title generated from the slug (e.g., "Convert Video").
   * Generated by converting kebab-case to Title Case.
   */
  title: string

  /**
   * Description from frontmatter (optional).
   * Empty string if not provided in frontmatter.
   */
  description: string

  /**
   * Array of allowed tools parsed from frontmatter (optional).
   * Empty array if not provided.
   */
  allowedTools: string[]

  /**
   * Argument hint from frontmatter (optional).
   * Empty string if not provided.
   */
  argumentHint: string

  /**
   * Markdown content without frontmatter.
   * This is the body of the markdown file.
   */
  content: string

  /**
   * Complete raw markdown content including frontmatter.
   * This is what users will copy when using the copy button.
   */
  rawContent: string

  /**
   * ISO 8601 formatted last modified date (optional).
   * Format: YYYY-MM-DDTHH:mm:ss.sssZ
   */
  lastModified?: string
}

/**
 * Converts a kebab-case filename to Title Case.
 *
 * @param slug - The filename slug (e.g., "convert-video")
 * @returns Title Case string (e.g., "Convert Video")
 *
 * @example
 * ```typescript
 * slugToTitle("convert-video") // => "Convert Video"
 * slugToTitle("pr-description") // => "Pr Description"
 * ```
 */
export function slugToTitle(slug: string): string {
  return slug
    .split("-")
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ")
}

/**
 * Parses a comma-separated string into an array of trimmed strings.
 *
 * @param value - Comma-separated string (e.g., "Read, Write, Edit")
 * @returns Array of trimmed strings (e.g., ["Read", "Write", "Edit"])
 *
 * @example
 * ```typescript
 * parseCommaSeparated("Read, Write, Edit") // => ["Read", "Write", "Edit"]
 * parseCommaSeparated(undefined) // => []
 * parseCommaSeparated("") // => []
 * ```
 */
export function parseCommaSeparated(value: string | undefined): string[] {
  if (!value || value.trim() === "") return []
  return value.split(",").map(item => item.trim())
}

/**
 * Validates if a slug is safe for use in URLs.
 *
 * A valid slug contains only lowercase letters, numbers, hyphens, and underscores.
 *
 * @param slug - The slug to validate
 * @returns true if the slug is valid, false otherwise
 *
 * @example
 * ```typescript
 * isValidSlug("convert-video") // => true
 * isValidSlug("pr_description") // => true
 * isValidSlug("Invalid Slug!") // => false
 * ```
 */
export function isValidSlug(slug: string): boolean {
  return /^[a-z0-9_-]+$/.test(slug)
}
